language: go
go: 
 - tip

go_import_path: github.com/loklak/loklak_api_go

install:
 - go get github.com/hokaccha/go-prettyjson

matrix:
  allow_failures:
  - go: tip

script:
  - go install
  - go test
